### ISSUE TITLE
can not login 

### ISSUE THREAD

**Issue by ls4cfk** [CristianoYL/RestaurantAndroidApp#1]
Guest user button isn't working , also can Signup for a account

**Comment by CristianoYL** [comment]
Hi @ls4cfk, thanks for using the app. But it's just my personal project, I haven't implemented the guest login feature yet. Feel free to implement your own ideas!

**Comment by ls4cfk** [comment]
Understandable but SignUp has problem too , cant register user.
when i am trying to do it , it just shows error on input(black , without text)
I'll upload log soon.
