### ISSUE TITLE
restaurant.db not found

### ISSUE THREAD

**Issue by srichakradhar** [CristianoYL/RestaurantAndroidApp#2]
Not able to find restaurant.db the local database file.

**Comment by vietalj** [comment]
Where Did you leave your restaurant.db?

**Comment by vietalj** [comment]
Or If you don't have, you need run run.py

**Comment by CristianoYL** [comment]
It's auto-generated by Flask-SQLAlchemy, if you're using local SQLite. Otherwise, you will need to create the database in your database system, PostgreSQL for example.

I believe this issue should be related to the Restaurant REST API repo, not the android repo.
